### PR TITLE
Created a grid for the photos in projects

### PR DESCRIPTION
**Pull request by tventura94**
made a display grid on the projects class and aligned the boxes as a grid

### CODE REVIEW

**Review by lotus-pocus — COMMENTED** [review]
Thank you tventura94, this is super helpful!

**Comment by tventura94** [comment]
Did you use it? Or do I need to reupload?

**Comment by lotus-pocus** [comment]
Hi there, sorry, this is my first time trying to get help on github. Still trying to work out how to utilize the platform and how everything works. I have been comparing the code you posted to what I have on vs code and working it out that way. I didn't realize I could download your fix.

**Comment by tventura94** [comment]
It's all good man - typically you'll like commit my branch to the main branch and then it gives me credit on my portfolio but it's all good dude enjoy!

**Pull request closed without merging**
